프로젝트 업로드 폼 자잘한 버그 fix
sopt-makers/sopt-internal-frontend pull request #86
Opened 2022-10-17 17:07 UTC by NamJwong

### 🤫 쉿, 나한테만 말해줘요. 이슈넘버
- close #84

### 🧐 어떤 것을 변경했어요~?
1. **Input, TextArea 컴포넌트의 count 값이 UI에 업데이트 되지 않는 버그를 고쳤어요**

props가 html 속성 타입을 extends하고 있어서 value와 onChange가 덮어씌워지는 것이 문제였습니다
그래서 아래와 같이 Omit 유틸리티 타입을 활용하는 방식을 시도해봤는데 안됐습니다
```tsx
export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> {
  error?: boolean;
  count?: boolean;
  maxCount?: number;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(({ error, count, maxCount, ...props }, ref) => {
  const [value, setValue] = useState<string>('');

  return (
    <>
      <StyledInput value={value} onChange={(e) => setValue(e.target.value)} error={error} ref={ref} {...props} />
      {count && (
        <StyledCountValue>
          <Text color={colors.gray100} typography='SUIT_12_M'>
            {`${value.length}/${maxCount}`}
          </Text>
        </StyledCountValue>
      )}
    </>
  );
});
```

그래서 현재와 같이 props의 순서를 바꾸는 방법으로 고쳤습니다
위 방법이 왜 안되는지 못찾았는데 일단 현재 방법으로 해도 문제 없다 생각해서 일단 올립니다 ... (왜 안되는지 궁금해요ㅠ)

2. **RHFControllerFormItem 컴포넌트에서 prop으로 받는 컴포넌트에, maxCount prop만큼 value 길이 제한을 해주었어요**
maxLength 설정이 안되고 있던 것이 문제라 추가했습니다

2022-10-18 01:48 UTC, juno7803 requested changes
예전엔 왜 됐는지 무슨생각으로 저렇게 짰는지 잘 모르겠네여..ㅎㅎ,,
근데 이렇게 하면 쓰는쪽에서 `value`를 못 읽을것 같은데요? (뒤의 컴포넌트 내부의 상태 `value`로 오버리아딩 되어서) 제 잘못이므로 이따 저도 방법을 찾아보겠습니다 🥲

2022-10-19 16:50 UTC, NamJwong commented
@juno7803 감사합니다 ㅜ ㅜ 말씀하신 것처럼 value를 읽지 못해서 해당 커밋 revert 하고 다른 방법으로 다시 했습니다

2022-10-19 16:51 UTC, NamJwong commented
그리고 이전 커밋 버그를 버스라고 한 거 끔찍하네요 스쿼시 머지 하겠습니다 . .

2022-10-19 17:29 UTC, juno7803 approved these changes
LGTM 👍

2022-10-19 17:29 UTC, juno7803 commented
@NamJwong 아니면 리버트 말고 리셋은 어때요?

2022-10-21 13:20 UTC, merged